Repository HE-Arc/SousMot, pull requests merged in 2022-04, with the labels that each got.

#32 feat(#16): Rules View
  sousmot/sousmotapp/static/scss/main.scss
  sousmot/sousmotapp/templates/sousmotapp/base.html
  sousmot/sousmotapp/templates/sousmotapp/rules.html
  sousmot/sousmotapp/urls.py
  sousmot/sousmotapp/views.py
Labels: Frontend

#33 chore(#27): Add settings for production
  sousmot/.env.example
  sousmot/sousmot/settings.py
Labels: Backend, Primary

#35 feat(#34): add mysqlclient in requirements.txt
  requirements.txt
Labels: Backend

#31 feat(#14): View Game
  sousmot/sousmotapp/static/js/game.js
  sousmot/sousmotapp/static/scss/main.scss
  sousmot/sousmotapp/templates/sousmotapp/game.html
  sousmot/sousmotapp/urls.py
  sousmot/sousmotapp/views.py
Labels: Frontend, Primary

#36 feat(#15): View lobby
  sousmot/sousmotapp/static/js/app.js
  sousmot/sousmotapp/static/scss/main.scss
  sousmot/sousmotapp/templates/sousmotapp/lobby.html
  sousmot/sousmotapp/urls.py
  sousmot/sousmotapp/views.py
Labels: Frontend, Primary

#38 actions(#37): restart uwsgi server with capristano
  config/deploy/production.rb
Labels: bug

#39 feat(#3): Create game view
  sousmot/sousmotapp/forms.py
  sousmot/sousmotapp/migrations/0002_game_in_game_game_uuid_alter_game_dictionary_and_more.py
  sousmot/sousmotapp/models.py
  sousmot/sousmotapp/templates/sousmotapp/index.html
  sousmot/sousmotapp/templates/sousmotapp/lobby.html
  sousmot/sousmotapp/urls.py
  sousmot/sousmotapp/views.py
Labels: Backend
