Repository HE-Arc/SousMot, pull requests merged in 2022-03, with the labels that each got.

#22 feat(#12): Create Index Home
  sousmot/sousmotapp/static/js/app.js
  sousmot/sousmotapp/static/scss/bulma-slider/index.sass
  sousmot/sousmotapp/static/scss/main.scss
  sousmot/sousmotapp/templates/sousmotapp/base.html
  sousmot/sousmotapp/templates/sousmotapp/index.html
  sousmot/sousmotapp/urls.py
  sousmot/sousmotapp/views.py
Labels: Frontend

#21 feat(#1): Create models and database
  sousmot/sousmotapp/admin.py
  sousmot/sousmotapp/migrations/0001_initial.py
  sousmot/sousmotapp/models.py
Labels: Backend, Database, Primary

#24 chore(#23): Hide the secrets from the eyes of the public !
  .github/workflows/deploy.yml
  .gitignore
  README.md
  requirements.txt
  sousmot/.env.example
  sousmot/sousmot/settings.py
Labels: documentation, Backend

#26 feat(#13): View Login and Sign Up
  sousmot/sousmot/settings.py
  sousmot/sousmot/urls.py
  sousmot/sousmotapp/static/scss/main.scss
  sousmot/sousmotapp/templates/registration/login.html
  sousmot/sousmotapp/templates/registration/signup.html
  sousmot/sousmotapp/templates/sousmotapp/base.html
  sousmot/sousmotapp/urls.py
  sousmot/sousmotapp/views.py
Labels: Frontend, Primary
